"""add analyses table

Revision ID: 3ee8349b6efa
Revises: 49498646bb28
Create Date: 2026-05-24 15:38:10.889460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ee8349b6efa'
down_revision: Union[str, Sequence[str], None] = '49498646bb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.String(length=50), nullable=False),
    sa.Column('business_logic_score', sa.Float(), nullable=True),
    sa.Column('strategy_strength_score', sa.Float(), nullable=True),
    sa.Column('analytical_depth_score', sa.Float(), nullable=True),
    sa.Column('financial_soundness_score', sa.Float(), nullable=True),
    sa.Column('communication_clarity_score', sa.Float(), nullable=True),
    sa.Column('framework_utilization_score', sa.Float(), nullable=True),
    sa.Column('overall_presentation_quality_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_elements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('investor_questions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('consultant_feedback', sa.Text(), nullable=True),
    sa.Column('raw_llm_output', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_analysis_status'), 'analyses', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_presentation_id'), 'analyses', ['presentation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_presentation_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_analysis_status'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
