"""add framework detection fields

Revision ID: 49498646bb28
Revises: db2137eabff8
Create Date: 2026-05-23 14:46:51.880278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49498646bb28'
down_revision: Union[str, Sequence[str], None] = 'db2137eabff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('primary_framework', sa.String(length=100), nullable=True))
    op.add_column('slides', sa.Column('framework_confidence', sa.Float(), nullable=True))
    op.add_column('slides', sa.Column('framework_reason', sa.Text(), nullable=True))
    op.add_column('slides', sa.Column('framework_matches', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.create_index(op.f('ix_slides_primary_framework'), 'slides', ['primary_framework'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_primary_framework'), table_name='slides')
    op.drop_column('slides', 'framework_matches')
    op.drop_column('slides', 'framework_reason')
    op.drop_column('slides', 'framework_confidence')
    op.drop_column('slides', 'primary_framework')
    # ### end Alembic commands ###
