"""add reasoning audit fields to analyses

Revision ID: c2b99b39df2b
Revises: cfe93267a138
Create Date: 2026-05-24 23:41:30.219029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2b99b39df2b'
down_revision: Union[str, Sequence[str], None] = 'cfe93267a138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('prompt_alignment_score', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('evidence_grounding_score', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('slide_insights', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('analyses', sa.Column('unsupported_claims', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('analyses', sa.Column('reasoning_gaps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'reasoning_gaps')
    op.drop_column('analyses', 'unsupported_claims')
    op.drop_column('analyses', 'slide_insights')
    op.drop_column('analyses', 'evidence_grounding_score')
    op.drop_column('analyses', 'prompt_alignment_score')
    # ### end Alembic commands ###
