"""add slide classification fields

Revision ID: db2137eabff8
Revises: 155c73a576c4
Create Date: 2026-05-23 14:08:49.638189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2137eabff8'
down_revision: Union[str, Sequence[str], None] = '155c73a576c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('slide_category', sa.String(length=80), nullable=True))
    op.add_column('slides', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('slides', sa.Column('classification_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_slides_slide_category'), 'slides', ['slide_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_slide_category'), table_name='slides')
    op.drop_column('slides', 'classification_reason')
    op.drop_column('slides', 'classification_confidence')
    op.drop_column('slides', 'slide_category')
    # ### end Alembic commands ###
